### ISSUE TITLE
not an issue - nextjs fyi

### ISSUE THREAD

**Issue by johndpope** [tfasoft/api#2]
I worked on a javascript nodejs project that had similar looking code to this.
You should checkout nextjs
https://nextjs.org/
it has a nice out of the box way to do routing (see screen shot below) - so everything is neatly compartmentalized and you get a lot of stuff out of the box.

also - typescript is going to save your bacon at some point.
<img width="303" alt="3" src="https://user-images.githubusercontent.com/289994/184733572-1516ada3-a6cb-48e0-a92c-461d0a2a2aa8.png">

/**
 * @file Defines all routes for the Properties route.
 */

import { retrieveAssetsByUser, createAsset, deleteAssetByAssetId } from '../../../db/queries';
import type { NextApiRequest, NextApiResponse } from 'next';
```typescript

/**
 *
 * @param {string} userId the user ID of the active user.
 * @param {string} description the description of the property.
 * @param {number} value the numerical value of the property.
 */
 export default (req: NextApiRequest, res: NextApiResponse) => {
  try{
      switch (req.method?.toUpperCase()) {
          case "GET":
              _get(req,res);
              break;
          case "POST":
              _post(req,res);
              break;
          case "PUT":
              _put(req,res);
              break;
          case "DELETE":
              _delete(req,res);
              break;
          default:
              res.status(404).send("{error:'not found'");
              break;
      }
  } catch (e){
      console.debug("error:",e);
      res.status(500).json({ e });
  }
};
/**
 * Retrieves property for a single user
 *
 * @param {string} userId the ID of the user.
 * @returns {Object[]} an array of properties
 */
async function _get(req: NextApiRequest, res: NextApiResponse){
  const accountId = req.query.id;
  const userId  = req.query.userId;
  const assets = await retrieveAssetsByUser(userId);
  res.status(200).send(assets);
}

async function _post(req: NextApiRequest, res: NextApiResponse){
  const { userId, description, value } = req.body;
  const newAsset = await createAsset(userId, description, value);
  res.json(newAsset);
}

function _put(req: NextApiRequest, res: NextApiResponse){
  res.status(200).send("PUT");
}
/**
 * Deletes an asset by its id
 *
 * @param {string} assetId the ID of the asset.
 */
async function _delete(req: NextApiRequest, res: NextApiResponse){

  const  assetId  = req.query.assetId;
  await deleteAssetByAssetId(assetId);

  res.status(204);
}







```

**Comment by johndpope** [comment]
nextjs will also collapse the frontend code into one repo  - will run unified process on the box.

**Comment by BlackIQ** [comment]
Hi John,

Thanks a lot for this great idea and for the valuable time your spend.
Really I don't know NextJs but your information about it and your example made me to learn NextJs as soon as possible.

I am very grateful. Honestly I wanted to send you message in LinkedIn to have a little talk. If you are comfortable with Email, I can send you email.

So, Let me learn NextJs first, then I will migrate all Express in NextJs.

Hope to talk with you soon.
Thanks again.

Amirhossein.
